/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But we want to manually specify the sidebar for more control
  docs: [
    'intro',
    'getting-started',
    'examples/index',
    'concepts/index',
    'guides/index',
    'integrations/index',
    'production/index',
    'telemetry',
    'roadmap',
    'contributing',
    'troubleshooting',
    'about',
    'reference/index',
  ],
  examples: [
    {
      type: 'link',
      label: '← Home',
      href: '/'  
    },
    'examples/index',
    {
      type: 'category',
      label: 'Data Type Examples',
      collapsed: false,
      className: 'category-header',
      items: [
        'examples/data-type/example-text',
        'examples/data-type/example-pdfs',
        'examples/data-type/example-images',
        'examples/data-type/example-audio',
        'examples/data-type/example-video',
      ],
    },
    {
      type: 'category',
      label: 'Use Cases',
      collapsed: false,
      className: 'category-header',
      items: [
        'examples/use-cases/image-search',
        'examples/use-cases/question-answering',
        'examples/use-cases/summarization',
      ],
    },
    {
      type: 'category',
      label: 'Popular Tools Examples',
      collapsed: false,
      className: 'category-header',
      items: [
        'examples/popular-tools/langchain',
        'examples/popular-tools/llama-index',
        'examples/popular-tools/haystack',
        'examples/popular-tools/unstructured',
      ],
    },
  ],
  concepts: [
    {
      type: 'link',
      label: '← Home',
      href: '/'  
    },
    'concepts/index',
    {
      type: 'category',
      label: 'Main Concepts',
      collapsed: false,
      className: 'category-header',
      items: [
        'concepts/embeddings',
        'concepts/vector-search',
        'concepts/metadata',
        'concepts/indexes',
        'concepts/distance-functions',
        'concepts/clients',
        'concepts/collections',
      ],
    },
  ],
  guides: [
    {
      type: 'link',
      label: '← Home',
      href: '/'  
    },
    'guides/index',
    {
      type: 'category',
      label: 'Usage Guide',
      collapsed: false,
      className: 'category-header',
      items: [
        'guides/persistent-chroma',
        'guides/running-chroma',
        'guides/docker',
      ],
    },
    {
      type: 'category',
      label: 'Metadata',
      collapsed: false,
      className: 'category-header',
      items: [
        'guides/metadata/keyword-search',
        'guides/metadata/additional-information',
        'guides/metadata/filter',
      ],
    },
    {
      type: 'category',
      label: 'Collections',
      collapsed: false,
      className: 'category-header',
      items: [
        'guides/collections/creating',
        'guides/collections/data-addition',
        'guides/collections/updating',
        'guides/collections/upserting',
        'guides/collections/deleting',
        'guides/collections/querying',
        'guides/collections/distance-function',
        'guides/collections/filtering',
      ],
    },
  ],
  integrations: [
    {
      type: 'link',
      label: '← Home',
      href: '/'  
    },
    'integrations/index',
    {
      type: 'category',
      label: 'Integrations',
      collapsed: false,
      className: 'category-header',
      items: [
        'integrations/langchain',
        'integrations/llama-index',
        'integrations/braintrust',
        'integrations/openllmetry',
        'integrations/streamlit',
        'integrations/haystack',
      ],
    },
  ],
  production: [
    {
      type: 'link',
      label: '← Home',
      href: '/'  
    },
    'production/index',
    {
      type: 'category',
      label: 'Production',
      collapsed: false,
      className: 'category-header',
      items: [
        'production/deployment/index',
        'production/observability',
        'production/performance',
        'production/authentication',
        'production/security',
        'production/logging',
        'production/administration',
        'production/migration',
        'production/restore',
      ],
    },
  ],
  deployment: [
    {
      type: 'link',
      label: '← Production',
      href: '/production'  
    },
    'production/deployment/index',
    {
      type: 'category',
      label: 'Deployment',
      collapsed: false,
      className: 'category-header',
      items: [
        'production/deployment/deployment-gcp',
        'production/deployment/deployment-aws',
      ],
    },
  ],
  reference: [
    {
      type: 'link',
      label: '← Home',
      href: '/'  
    },
    'reference/index',
    'reference/api-reference',
    {
      type: 'category',
      label: 'Python Client',
      collapsed: false,
      className: 'category-header',
      items: [
        'reference/python-client/client',
        'reference/python-client/collection',
      ],
    },
    {
      type: 'category',
      label: 'JS/TS Client',
      collapsed: false,
      className: 'category-header',
      items: [
        'reference/js-ts-client/client',
        'reference/js-ts-client/collection'
      ],
    },
  ],
};

module.exports = sidebars;
